force-app/main/default/objects/Assigned_Resource__c/Assigned_Resource__c.object-meta.xml
<CustomObject>
    <label>Assigned Resource1</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Assigned Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned ResourceS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ladminai-appointment/main/default/objects/Assigned_Resource__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment__c</referenceTo>
    <relationshipName>Assigned_ResourceS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ladminai-appointment/main/default/objects/Assigned_Resource__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>Service_Resource__c</referenceTo>
    <relationshipName>Assigned_ResourceS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Config__mdt/Component_Config__mdt.object-meta.xml
<CustomObject>
    <label>Component_Config</label>
    <pluralLabel>Component_Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Component_Config__mdt/fields/ExpiryDateTime__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDateTime__c</fullName>
    <label>ExpiryDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Booked_By__c.field-meta.xml
<CustomField>
    <fullName>Booked_By__c</fullName>
    <description>lvl 2 booker</description>
    <label>Booked By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_Team</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Inhouse_Created_By__c.field-meta.xml
<CustomField>
    <fullName>Inhouse_Created_By__c</fullName>
    <label>Platform Created By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Created_By1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Referral_Details__c.field-meta.xml
<CustomField>
    <fullName>Referral_Details__c</fullName>
    <label>Referral Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referral_Subject__c.field-meta.xml
<CustomField>
    <fullName>Referral_Subject__c</fullName>
    <label>Referral Subject</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Resource_Availability__c/Resource_Availability__c.object-meta.xml
<CustomObject>
    <label>Resource Availability</label>
    <nameField>
        <label>Resource Availability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Availabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ladminai-appointment/main/default/objects/Resource_Availability__c/fields/Break_End__c.field-meta.xml
<CustomField>
    <fullName>Break_End__c</fullName>
    <label>Break End</label>
    <type>Time</type>
</CustomField>

ladminai-appointment/main/default/objects/Resource_Availability__c/fields/Break_Start__c.field-meta.xml
<CustomField>
    <fullName>Break_Start__c</fullName>
    <label>Break Start</label>
    <type>Time</type>
</CustomField>

ladminai-appointment/main/default/objects/Resource_Availability__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>Service_Resource__c</referenceTo>
    <relationshipLabel>Resource Availabilities</relationshipLabel>
    <relationshipName>Resource_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Resource__c/Service_Resource__c.object-meta.xml
<CustomObject>
    <label>Service Resource1</label>
    <nameField>
        <label>Service Resource</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Resource__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Resource__c/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment__c/ServiceAppointment__c.object-meta.xml
<CustomObject>
    <label>Service Appointment1</label>
    <nameField>
        <label>Service Appointment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceAppointment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Service_Appointment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment__c/fields/Appointment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Mode__c</fullName>
    <label>Booking Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Answer4U</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Facebook Chat</fullName>
            </value>
            <value>
                <fullName>Groupon</fullName>
            </value>
            <value>
                <fullName>Hair Calculator</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Self Generated</fullName>
            </value>
            <value>
                <fullName>TikTok</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>VFT Funnel</fullName>
            </value>
            <value>
                <fullName>B2B Referral</fullName>
            </value>
            <value>
                <fullName>Spam</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment__c/fields/Booked_By__c.field-meta.xml
<CustomField>
    <fullName>Booked_By__c</fullName>
    <label>Booked By</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Status</fullName>
            </value>
            <value>
                <fullName>Ajay</fullName>
            </value>
            <value>
                <fullName>Alex</fullName>
            </value>
            <value>
                <fullName>Buddy</fullName>
            </value>
            <value>
                <fullName>Dean</fullName>
            </value>
            <value>
                <fullName>Haitham</fullName>
            </value>
            <value>
                <fullName>Hakeem</fullName>
            </value>
            <value>
                <fullName>Harry</fullName>
            </value>
            <value>
                <fullName>HSHC</fullName>
            </value>
            <value>
                <fullName>Joel</fullName>
            </value>
            <value>
                <fullName>Mahmoud</fullName>
            </value>
            <value>
                <fullName>Matt F</fullName>
            </value>
            <value>
                <fullName>Rashid</fullName>
            </value>
            <value>
                <fullName>Sean</fullName>
            </value>
            <value>
                <fullName>Sulaiman</fullName>
            </value>
            <value>
                <fullName>Yaseen</fullName>
            </value>
            <value>
                <fullName>Yusaf</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment__c/fields/Lead_Stage_at_Booking__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage_at_Booking__c</fullName>
    <label>Lead Stage at Booking</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ladminai-appointment/main/default/objects/ServiceAppointment__c/fields/Parent_Record1__c.field-meta.xml
<CustomField>
    <fullName>Parent_Record1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Record</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Service Appointment</relationshipLabel>
    <relationshipName>Service_Appointment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment__c/fields/Scheduled_End__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_End__c</fullName>
    <label>Scheduled End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment__c/fields/Scheduled_end_text__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_end_text__c</fullName>
    <label>Scheduled end text</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment__c/fields/Scheduled_Start__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Start__c</fullName>
    <label>Scheduled Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment__c/fields/Scheduled_start_text__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_start_text__c</fullName>
    <label>Scheduled start text</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment__c/fields/Service_Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource_Name__c</fullName>
    <label>Service Resource Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>DNA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Createappointmentreferralcontroller.cls
public class Createappointmentreferralcontroller {
 
   @AuraEnabled
public static Boolean isComponentExpired(String componentName) {
    try {
        Component_Config__mdt cfg = [ SELECT ExpiryDateTime__c FROM Component_Config__mdt WHERE DeveloperName = :componentName LIMIT 1];
        if (cfg == null || cfg.ExpiryDateTime__c == null) {
             return false;
        }
        DateTime nowUTC = System.now();
        TimeZone ukTimeZone = TimeZone.getTimeZone('Europe/London');
        Integer offsetMillis = ukTimeZone.getOffset(nowUTC);
        DateTime nowUK = nowUTC.addSeconds(offsetMillis / 1000);
        Boolean expired = nowUK > cfg.ExpiryDateTime__c;
        return expired;
        
    } catch (Exception e) {
        return false;
    }
}
    @AuraEnabled
    public static String getLeadName(String leadId) {
        Lead leadRecord = [SELECT Name FROM Lead WHERE Id = :leadId LIMIT 1];
        return leadRecord.Name;
    }
    
    @Auraenabled
    public static lead convertToDateTime(String reffSubject, String bookedBy , String reffDeatils, string objid,string[] starttime, Date startDate,string emailAddress,string eventName,String bookingSource,String leadName,string bookingstatus){
                                             System.debug('### METHOD CALLED ###');

                                             string singleStartTime=starttime[0];
                                             string formatDate=startDate.format();
                                             string newDateTime=formatDate+', '+singleStartTime;
                                             Datetime startDateTymInstnce=Datetime.parse(newDateTime);
                                             Datetime endDateTymInstnce=startDateTymInstnce.addMinutes(30);
                                             String dateTimeCheck='('+String.valueOf(startDateTymInstnce.format('MM/dd/yyyy hh:mm a'))+', '+String.valueOf(endDateTymInstnce.format('MM/dd/yyyy hh:mm a'))+')';  //'(03/24/2023 09:00 AM, 03/24/2023 09:30 AM)'
                                             
                                             Lead led =[Select id, Name , Status from Lead where Id=: objid];
                                             string loginName=UserInfo.getFirstName()+' '+UserInfo.getLastName();
                                             map<string,list<String>> serwitSA= new map<string,list<String>>();
                                             Set<String> serviceKeyset=new Set<String>();
                                             list<String>serviceKeysetlist= new list<String>();
                                             Service_Resource__c srObj = new Service_Resource__c();
                                             Map<String,Service_Resource__c> serviceResMap = new  Map<String,Service_Resource__c>(); 
                                             
                                             list<Service_Resource__c>  InatlizeSRwithnull = new list<Service_Resource__c>();
                                             List<Service_Resource__c> serResObj=[SELECT Id,Name,RelatedRecordId__c,Active__c,RelatedRecordId__r.IsActive FROM Service_Resource__c Where Active__c=true and RelatedRecordId__r.IsActive=true ];
                                             
                                             for(Service_Resource__c srsource :serResObj){
                                                 serwitSA.put(srsource.Name,new List<String>());
                                                 serviceResMap.put(srsource.Name,srsource);
                                             }
                                                 list<ServiceAppointment__c> sachecklist=[SELECT Id, Account__c, Scheduled_Start__c, Scheduled_End__c, Service_Resource_Name__c, Scheduled_start_text__c, Scheduled_end_text__c FROM ServiceAppointment__c where Scheduled_start_text__c LIKE :'%'+formatDate+'%' ORDER BY CreatedDate ASC];
                                                 for(ServiceAppointment__c sr :sachecklist){
                                                     string srtappiont='('+string.valueOf(sr.Scheduled_start_text__c)+', '+string.valueOf(sr.Scheduled_end_text__c)+')';
                                                     if (serwitSA.containsKey(sr.Service_Resource_Name__c)) {
                                                         serwitSA.get(sr.Service_Resource_Name__c).add(srtappiont);
                                                         
                                                     }      
                                                 }
                                                 serviceKeyset=serwitSA.keyset();
                                                 serviceKeysetlist.addAll(serviceKeyset);   
                                             
                                             if(eventName!=null){
                                                 srObj=[Select Name,RelatedRecordId__c from Service_Resource__c where Id=:eventName];
                                              }
                                             User usrObj=[Select Name,Email from User where Id=:srObj.RelatedRecordId__c];
                                             string usrEmail=String.valueOf(usrObj.Email);
                                             if(led!=null){
                                                 led.Referral_Subject__c=reffSubject;
                                                 led.Referral_Details__c=reffDeatils;
                                                 update led;
                                             }
                                              System.debug('led '+led);
                                             ServiceAppointment__c sp =  new ServiceAppointment__c();
                                             sp.Subject__c=reffSubject;
                                             sp.Booked_By__c =String.valueOf(bookedBy);
                                             sp.Parent_Record1__c = led.Id;
                                             sp.Status__c='Scheduled';
                                             sp.Service_Resource_Name__c=srObj.Name;
                                             sp.Scheduled_Start__c = startDateTymInstnce; 
                                             sp.Scheduled_End__c = endDateTymInstnce;
                                             sp.Scheduled_start_text__c=startDateTymInstnce.format();
                                             sp.Scheduled_end_text__c=endDateTymInstnce.format();
                                             sp.Appointment_Mode__c = String.valueOf(bookingSource);
                                             sp.Name = leadName;
                                             sp.Status__c = bookingstatus;
                                             sp.Lead_Stage_At_Booking__c = led.Status;

                                             insert sp;
                                             System.debug('sp '+sp);
                                             Event evtObj=new Event();
                                             evtObj.Subject=led.Referral_Subject__c;
                                             evtObj.WhoId=led.Id;
                                             evtObj.start_date_time__c=String.valueOf(startDateTymInstnce.format('MM/dd/yyyy hh:mm a'));
                                             evtObj.End_Date_Time__c=String.valueOf(endDateTymInstnce.format('MM/dd/yyyy hh:mm a'));
                                             evtObj.OwnerId=srObj.RelatedRecordId__c;
                                             Long dt1Long = startDateTymInstnce.getTime();
                                             Long dt2Long = endDateTymInstnce.getTime();
                                             Long milliseconds = dt2Long - dt1Long;
                                             Long seconds = milliseconds / 1000;
                                             Long minutes = seconds / 60;
                                             evtObj.DurationInMinutes=Integer.valueof(minutes);
                                             evtObj.ActivityDateTime=startDateTymInstnce;
                                             evtObj.Status__c = sp.Status__c;
                                             insert evtObj;
                                             
                                             Assigned_Resource__c ar=new Assigned_Resource__c();
                                             ar.Service_Appointment__c=sp.Id;
                                             ar.Service_Resource__c=srObj.Id;
                                                 insert ar;
                                             return led;
                                         }
    @Auraenabled
    public static string getUserName(){
        string loginName=UserInfo.getFirstName()+' '+UserInfo.getLastName();
        return loginName;
    }
    
    @Auraenabled
    public static String getPiklistValues1(String RecordId) {
        string EmailValue='';
        lead led = [Select id,Name,Email from Lead where Id =: RecordId limit 1];
        if(led.Email!=null) EmailValue=led.Email;
        return EmailValue;
    }
    @AuraEnabled
    public static void setObjectToRecentItems(Id recordId) {
        if (!String.isBlank(recordId)) {
            Schema.SObjectType sObjectType = recordId.getSobjectType();
            String queryString = String.format('SELECT Id, Name FROM {0} WHERE Id =: recordId FOR VIEW', new List<Object>{sObjectType});
            system.debug(queryString);
            Database.query(queryString);}
        
    }
  
@AuraEnabled
public static List<List<String>> availableStartTimeSlot(String serResId, Date schedstrttime) {
    List<List<String>> finalSlots = new List<List<String>>();

    if (serResId == null || schedstrttime == null) {
        return finalSlots;
    }
    Datetime dt = Datetime.newInstance(schedstrttime.year(), schedstrttime.month(), schedstrttime.day(), 0, 0, 0);
    String weekday = dt.format('EEEE'); 
    List<Resource_Availability__c> availList = [
        SELECT Id, Name, Day_Of_Week__c, Start_Time__c, End_Time__c, Break_Start__c, Break_End__c, Is_Active__c
        FROM Resource_Availability__c
        WHERE Service_Resource__c = :serResId
        AND Day_Of_Week__c = :weekday
        AND Is_Active__c = true
    ];

    if (availList.isEmpty()) {
        return finalSlots;
    }
    for (Resource_Availability__c avail : availList) {
        if (avail.Start_Time__c == null || avail.End_Time__c == null) {
            continue;
        }

        Time startTime = avail.Start_Time__c;
        Time endTime = avail.End_Time__c;
        Time breakStart = avail.Break_Start__c;
        Time breakEnd = avail.Break_End__c;

        if (startTime >= endTime) {
            continue;
        }

        Integer slotMinutes = 30;
        Time cursor = startTime;

        while (cursor.addMinutes(slotMinutes) <= endTime) {
            Time next = cursor.addMinutes(slotMinutes);
			Boolean skip = false;
            if (breakStart != null && breakEnd != null) {
                if ((cursor >= breakStart && cursor < breakEnd) ||
                    (next > breakStart && next <= breakEnd)) {
                    skip = true;
                }
            }

            if (!skip) {
                String startHour   = String.valueOf(cursor.hour());
                String startMinute = String.valueOf(cursor.minute());
                String endHour     = String.valueOf(next.hour());
                String endMinute   = String.valueOf(next.minute());

                if (startHour.length() == 1) startHour = '0' + startHour;
                if (startMinute.length() == 1) startMinute = '0' + startMinute;
                if (endHour.length() == 1) endHour = '0' + endHour;
                if (endMinute.length() == 1) endMinute = '0' + endMinute;

                String startStr = startHour + ':' + startMinute;
                String endStr   = endHour + ':' + endMinute;

                finalSlots.add(new List<String>{ startStr, endStr });
            }
            cursor = next;
        }
    }
    return finalSlots;
}
   
    @AuraEnabled
    public static string returnAccountName (string recid)
    {
        Account accObj=[select name from account where id=:recid];
        return String.valueOf(accObj.name);
    }
    @AuraEnabled
    public static string fetchContactEmail (string conid)
    {
        Contact conObj=[select id,name,email from contact where id=:conid];
        return String.valueOf(conObj.email);
    }
    
    //*********** A C H STARTS******************************
      @AuraEnabled
public static String getInhouseCreatedBy(Id recordId) {
    if (recordId == null) return null;

    Lead ld = [
        SELECT Inhouse_Created_By__c
        FROM Lead
        WHERE Id = :recordId
        LIMIT 1
    ];

    return ld.Inhouse_Created_By__c;

}
    
    @AuraEnabled
public static List<String> getBookedByPicklistValues() {
    List<String> values = new List<String>();

    Schema.DescribeFieldResult dfr =
        Lead.Booked_By__c.getDescribe();

    for (Schema.PicklistEntry ple : dfr.getPicklistValues()) {
        if (ple.isActive()) {
            values.add(ple.getValue()); // API value
        }
    }
    return values;
}
@AuraEnabled
public static String getBookedByValue(Id recordId) {
    if (recordId == null) return null;

    return [
        SELECT Booked_By__c
        FROM Lead
        WHERE Id = :recordId
        LIMIT 1
    ].Booked_By__c;
}
@AuraEnabled
public static void updateBookedBy(Id recordId, String bookedBy) {
    if (recordId == null || String.isBlank(bookedBy)) return;

    update new Lead(
        Id = recordId,
        Booked_By__c = bookedBy
    );
}

// ************************************* ACH OVER*************************************
}